from __future__ import annotations

import csv
import sqlite3
from pathlib import Path
from collections.abc import Iterable

from app.participant.listing_row_parser import prepare_listing_row


def create_schema(connection: sqlite3.Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS listings (
            listing_id TEXT PRIMARY KEY,
            platform_id TEXT,
            scrape_source TEXT,
            title TEXT NOT NULL,
            description TEXT,
            processed_description TEXT,
            street TEXT,
            city TEXT,
            postal_code TEXT,
            canton TEXT,
            price INTEGER,
            rooms REAL,
            area REAL,
            available_from TEXT,
            latitude REAL,
            longitude REAL,
            distance_public_transport INTEGER,
            distance_shop INTEGER,
            distance_kindergarten INTEGER,
            distance_school_1 INTEGER,
            distance_school_2 INTEGER,
            transit_count_500m INTEGER,
            shops_count_500m INTEGER,
            parks_count_500m INTEGER,
            schools_count_500m INTEGER,
            hospitals_count_500m INTEGER,
            nightlife_count_500m INTEGER,
            pedestrian_zones_count_500m INTEGER,
            dist_to_transit_m INTEGER,
            nearest_transit_name TEXT,
            dist_to_shops_m INTEGER,
            dist_to_parks_m INTEGER,
            dist_to_schools_m INTEGER,
            dist_to_hospitals_m INTEGER,
            dist_to_nightlife_m INTEGER,
            dist_to_pedestrian_zones_m INTEGER,
            dist_to_lakes_m INTEGER,
            dist_to_rivers_m INTEGER,
            dist_to_noisy_roads_m INTEGER,
            dist_to_noisy_trains_m INTEGER,
            elevation_m REAL,
            weighted_crime_per_1000 REAL,
            feature_balcony INTEGER,
            feature_elevator INTEGER,
            feature_parking INTEGER,
            feature_garage INTEGER,
            feature_fireplace INTEGER,
            feature_child_friendly INTEGER,
            feature_pets_allowed INTEGER,
            feature_temporary INTEGER,
            feature_new_build INTEGER,
            feature_wheelchair_accessible INTEGER,
            feature_private_laundry INTEGER,
            feature_minergie_certified INTEGER,
            features_json TEXT NOT NULL,
            offer_type TEXT,
            object_category TEXT,
            object_type TEXT,
            original_url TEXT,
            images_json TEXT,
            location_address_json TEXT,
            orig_data_json TEXT,
            raw_json TEXT NOT NULL,
            status TEXT,
            time_of_creation TEXT,
            last_scraped TEXT,
            object_type_text TEXT,
            partner_name TEXT,
            price_type TEXT,
            agency_name TEXT,
            agency_phone TEXT,
            agency_email TEXT,
            floor INTEGER,
            year_built INTEGER,
            prop_balcony_raw INTEGER,
            prop_elevator_raw INTEGER,
            prop_parking_raw INTEGER,
            prop_garage_raw INTEGER,
            prop_fireplace_raw INTEGER,
            prop_child_friendly_raw INTEGER,
            animal_allowed_raw INTEGER,
            rent_gross_raw INTEGER,
            maybe_temporary_raw INTEGER,
            is_new_building_raw INTEGER,
            supermarket_name TEXT,
            avg_rent_for_room_type REAL,
            rent_vs_average REAL,
            crime_index_0_100 REAL,
            grocery REAL,
            dining REAL,
            cafes REAL,
            nightlife REAL,
            healthcare REAL,
            early_education REAL,
            education REAL,
            parks REAL,
            playgrounds REAL,
            sports REAL,
            cycling REAL,
            transit REAL,
            car_infra REAL,
            culture REAL,
            pet_friendly REAL,
            financial REAL,
            safety REAL,
            shopping REAL,
            personal_care REAL,
            accommodation REAL,
            coworking REAL,
            beaches REAL,
            total REAL,
            _livability REAL,
            _activity REAL,
            _liv_grade TEXT,
            _act_grade TEXT
        )
        """
    )
    connection.commit()


def import_csvs(connection: sqlite3.Connection, csv_paths: Iterable[Path]) -> None:
    for csv_path in csv_paths:
        with csv_path.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            rows = [prepare_listing_row(row) for row in reader]

            connection.executemany(
                """
                INSERT INTO listings (
                    listing_id,
                    platform_id,
                    scrape_source,
                    title,
                    description,
                    processed_description,
                    street,
                    city,
                    postal_code,
                    canton,
                    price,
                    rooms,
                    area,
                    available_from,
                    latitude,
                    longitude,
                    distance_public_transport,
                    distance_shop,
                    distance_kindergarten,
                    distance_school_1,
                    distance_school_2,
                    transit_count_500m,
                    shops_count_500m,
                    parks_count_500m,
                    schools_count_500m,
                    hospitals_count_500m,
                    nightlife_count_500m,
                    pedestrian_zones_count_500m,
                    dist_to_transit_m,
                    nearest_transit_name,
                    dist_to_shops_m,
                    dist_to_parks_m,
                    dist_to_schools_m,
                    dist_to_hospitals_m,
                    dist_to_nightlife_m,
                    dist_to_pedestrian_zones_m,
                    dist_to_lakes_m,
                    dist_to_rivers_m,
                    dist_to_noisy_roads_m,
                    dist_to_noisy_trains_m,
                    elevation_m,
                    weighted_crime_per_1000,
                    feature_balcony,
                    feature_elevator,
                    feature_parking,
                    feature_garage,
                    feature_fireplace,
                    feature_child_friendly,
                    feature_pets_allowed,
                    feature_temporary,
                    feature_new_build,
                    feature_wheelchair_accessible,
                    feature_private_laundry,
                    feature_minergie_certified,
                    features_json,
                    offer_type,
                    object_category,
                    object_type,
                    original_url,
                    images_json,
                    location_address_json,
                    orig_data_json,
                    raw_json,
                    status,
                    time_of_creation,
                    last_scraped,
                    object_type_text,
                    partner_name,
                    price_type,
                    agency_name,
                    agency_phone,
                    agency_email,
                    floor,
                    year_built,
                    prop_balcony_raw,
                    prop_elevator_raw,
                    prop_parking_raw,
                    prop_garage_raw,
                    prop_fireplace_raw,
                    prop_child_friendly_raw,
                    animal_allowed_raw,
                    rent_gross_raw,
                    maybe_temporary_raw,
                    is_new_building_raw,
                    supermarket_name,
                    avg_rent_for_room_type,
                    rent_vs_average,
                    crime_index_0_100,
                    grocery,
                    dining,
                    cafes,
                    nightlife,
                    healthcare,
                    early_education,
                    education,
                    parks,
                    playgrounds,
                    sports,
                    cycling,
                    transit,
                    car_infra,
                    culture,
                    pet_friendly,
                    financial,
                    safety,
                    shopping,
                    personal_care,
                    accommodation,
                    coworking,
                    beaches,
                    total,
                    _livability,
                    _activity,
                    _liv_grade,
                    _act_grade
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                rows,
            )
    connection.commit()


def create_indexes(connection: sqlite3.Connection) -> None:
    connection.execute("CREATE INDEX IF NOT EXISTS idx_listings_city ON listings(city)")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_listings_postal_code ON listings(postal_code)")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_listings_canton ON listings(canton)")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_listings_price ON listings(price)")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_listings_rooms ON listings(rooms)")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_listings_latitude ON listings(latitude)")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_listings_longitude ON listings(longitude)")
    connection.commit()
